DROP DATABASE IF EXISTS tienda;
CREATE DATABASE tienda;

USE tienda;

DROP TABLE IF EXISTS modelos;
CREATE TABLE modelos (
  IDMODELO char(2) NOT NULL,
  MARCA char(10) NOT NULL,
  TIPO char(10) NOT NULL,
  MOTOR char(10) NOT NULL,
  PRIMARY KEY (IDMODELO)
);

DROP TABLE IF EXISTS concesionarios;
CREATE TABLE concesionarios (
  IDCONCE char(2) NOT NULL,
  MODELO char(10) NOT NULL,
  CIUDAD char(10) NOT NULL,
  CALLE char(20) NOT NULL,
  PRIMARY KEY (IDCONCE)
); 

DROP TABLE IF EXISTS coches;
CREATE TABLE coches (
  IDCOCHE char(2) NOT NULL,
  PRECIO char(10) NOT NULL,
  YEAR char(10) NOT NULL,
  COLOR char(10) NOT NULL,
  PRIMARY KEY (IDCOCHE)
); 

DROP TABLE IF EXISTS tiendaModelo;
CREATE TABLE tiendaModelo (
  IDCONCE char(2) NOT NULL,
  IDCOCHE char(2) NOT NULL,
  COLOR char(10) NOT NULL,
  PRIMARY KEY (IDCONCE, IDCOCHE),
  FOREIGN KEY (IDCONCE) REFERENCES concesionarios (IDCONCE),
  FOREIGN KEY (IDCOCHE) REFERENCES coches (IDCOCHE)
); 
